package com.sculptee.utils.preferenceconstant

class PreferenceConstantParam {
    companion object{
        var isLogIn:String="islogin"
        var EVENTID:String="eventid"
        var EVENTNAME:String="eventname"
        var PRODUCTID:String="productid"
        var TOKEN:String="token"
        val CUSTOMER_ID="ID"
        val CUSTOMER_EMAIL="email"
        val PRODUCTNAME="pname"
        val TOTALVAL="total"
        var H_F_NAME="hfmae"
        var H_L_NAME="flname"
        var H_MOB="hmob"
        var H_STREET1="hstreet1"
        var H_STREET2="hstreet2"
        var H_ZIP="hzip"
        var O_F_NAME="omae"
        var O_L_NAME="olname"
        var O_MOB="omob"
        var O_STREET1="ostreet1"
        var O_STREET2="ostreet2"
        var O_ZIP="ozip"
        var O_COMPANY="0company"
        var H_COMPANY="hcompany"
        var ORDERID="o_id"
        var WISHLIST="wishlist"
        var SHIPPINGCOST="shippingcost"
        var PACKING_COST="packingcost"
        var ORDERGST="gst"
        var PAYVAL="payval"
        var SHIPMETHOD_ID="shipping_method_id"
        var SHIPMETHOD_TITLE="shipping_method_title"
        var FEE_PACKAGETITLE="fee_package_title"
        var FEE_TAX_STATUS="fee_tax_status"
        var PAY_AMOUNT="amount"
        var DEVICE_TOKEN="token"
        var DEVICE_IMEI="imei"
        var CUSTOMER_NAME="customername"
        var CUSTOMER_IMAGE="customerimage"
        var ISFOEM_LOGIN="fromlogin"
        var CUSTOMER_MOBILE="mobile"
        var ORDER_IDS="order_ids"

        var Deafult_F_name="def_fname"
        var Deafult_L_name="def_lname"
        var Deafult_Street_address1="def_str_address1"
        var Deafult_Street_Address2="def_str_address2"
        var Deafult_TownCity="def_towncity"
        var Deafult_state="def_state"
        var Deafult_Pin="pin"
        var DeafultAddressType="addresstype"

    }
}